### ISSUE TITLE
Dataset?

### ISSUE THREAD

**Issue by PyJulie** [wutong16/DistributionBalancedLoss#6]
Is the dataset first released by authors? where can I download the dataset you evaluated in your manuscript? Or is there any widely-accepted public dataset for multi-label long-tailed classification task?

**Comment by wutong16** [comment]
Yes.  The datasets we used are subsets extracted from the original COCO and VOC, and the annotation files are included in the repo under the `./appendix` folder.
Currently, we're not aware of widely-accepted public datasets for multi-label long-tailed _classification_, while LVIS is a popular dataset for _detection_, it's challenging to perform pure classification on it due to its complexity.
